<a href="https://colab.research.google.com/github/nclnngzmn/CpE-AIML/blob/main/58034_Lab02_Tyche.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> **Problem 4.c: Computational Programming (Also Laboratory 2)**

> Encode Equations 3.1 to 3.4 as the class `LRegression` wherein:

> * `LRegression` should be instantiated with a dataset $X$, a ground truth vector $y$, and a parameter vector $\theta$. Each parameter should have a data type of `numpy.array`.
> * It should further have `methods`reflecting to at least the four (4) aforementioned equations. Each should have a return value.


In [37]:
import numpy as np
from numpy import random

In [39]:
class LRegression():
  def __init__(self, X_array, y_GndTruth, thetaVector):
    self.X_array = X_array
    self.y_GndTruth = y_GndTruth
    self.thetaVector = thetaVector
  
  def getVectorMagnitude(self):
    magnitude = np.linalg.norm(self.thetaVector)
    return magnitude
  
  def getZ(self): #Eq. 3.1
    self.z = np.dot(self.X_array, self.thetaVector)
    return self.z

  def getActivation (self): #Eq. 3.2 & 3.3
    self.activation = 1/(1+np.exp(self.z))
    return self.activation

  def getLoss(self): #Eq. 3.4
    m = self.y_GndTruth.shape[0]
    yt = self.y_GndTruth.transpose()

    lossEq= (-1*yt)*(np.log(self.activation)) - ((1-self.y_GndTruth).transpose())*(np.log(1-self.activation))
    self.J = (1/m)*lossEq
    return self.J

In [40]:
X = np.array([[2,4,6],
              [1,7,9],
              [3,5,8],])
m = X.shape[1]
theta = np.random.normal(0, 1, size=(m, 1))
y = np.random.randint(0,2, size=(m,1))
Regression = LRegression(X, y, theta)

In [41]:
Regression.getVectorMagnitude()

0.7891778993674957

###Equation 3.1

$$ z = x^{(i)}\theta^{(i)} = X\cdot \theta\\_{\text{Eq. 3.1}}$$

In [42]:
Regression.getZ()

array([[-1.3802192 ],
       [-2.24928817],
       [-1.87928157]])

###Equation 3.2 and 3.3

$$ h_\theta(x) = g(z)\\_{\text{Eq. 3.2}}$$

$$g(z) = \frac{1}{1+e^{-z}}\\_{\text{Eq. 3.3}}$$

In [43]:
Regression.getActivation()

array([[0.7990262 ],
       [0.90458912],
       [0.86752858]])

###Equation 3.4

$$J(\theta) = \frac{1}{m} \sum^m_{i=0}=[-y^{(i)}\log({h_{\theta}(x^{(i)})})-(1-y^{(i)})\log(1-h_{\theta}(x^{(i)}))]\\_{\text{Eq. 3.4}}$$

In [44]:
Regression.getLoss()

array([[0.07478718, 0.07478718, 0.07478718],
       [0.03342482, 0.03342482, 0.03342482],
       [0.04736894, 0.04736894, 0.04736894]])