<a href="https://colab.research.google.com/drive/1CcqZO6kqBs0Z40SLxdQe5Xc4EujqJi0G" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topic02a : Prelim Problem Set I

## Case 1
Represent the following representations into its vectorized form using LaTeX.
> **Problem 1.a. System of Linear Equations**
$$
\left\{
    \begin{array}\\
        -y+z=\frac{1}{32}\\ 
        \frac{1}{2}x -2y=0 \\
        -x + \frac{3}{7}z=\frac{4}{5}
    \end{array}
\right. $$
> **Problem 1.b. Linear Combination**
$$  \cos{(\theta)}\hat{i} + \sin{(\theta)}\hat{j} - \csc{(2\theta)}\hat{k}$$
> **Problem 1.c. Scenario**
>
>A conference has 200 student attendees, 45 professionals, and has 15 members of the panel. There is a team of 40 people on the organizing committee. Represent the *percent* composition of each *attendee* type of the conference in matrix form.

Express your answers in LaTeX in the answer area.


In [2]:
import numpy as np
import math 
from numpy import random

### **Problem 1.a: System of Linear Equations**

$$ A = \begin{bmatrix} 0 & -1 & 1 &  \frac {1}{32} \\ \frac {1}{2} & -2 &  0 & 0 \\ -1 & 0 & \frac {3}{7} &  \frac {4}{5} \end{bmatrix}$$

### **Problem 1.b: Linear Combination**

$$ B = \begin{bmatrix} \sin{(\theta)} \\ \cos{(\theta)} \\ - \csc{(2\theta)} \end{bmatrix}$$

### **Problem 1.c: Scenario**

$$Percentage = \frac{No. of\:Attendee\:type \times 100}{Total\:Number\:of\:Attendees}$$

$$Students = \frac{200 \times 100}{300} = 66.67\%$$

$$Professionals = \frac{45 \times 100}{300} = 15.00\%$$

$$Panel\:Members = \frac{15 \times 100}{300} = 13.33\%$$

$$Organizing\:Committee = \frac{40 \times 100}{300} = 5.00\%$$

###<center>**Matrix form of percentage composition of each attendee type**

$$ Attendees = \begin{bmatrix} 
66.67\% \\ 
15.00\% \\ 
13.33\% \\ 
5.00\% 
\end{bmatrix} $$


# Case 2
> **Problem 2.a: Vector Magnitude**

>The magnitude of a vector is usually computed as:
$$||v|| = \sqrt{a_0^2 + a_1^2 + ... +a_n^2}$$
Whereas $v$ is any vector and $a_k$ are its elements wherein $k$ is the size of $v$.
Re-formulate $||v||$ as a function of an inner product. Further discuss this concept and provide your user-defined function.

> **Problem 2.b: Angle Between Vectors**

> Inner products can also be related to the Law of Cosines. The property suggests that:
$$u\cdot v = ||u||\cdot||v||\cos(\theta)$$
Whereas $u$ and $v$ are vectors that have the same sizes and $\theta$ is the angle between $u$ and $v$.

> Explain the behavior of the dot product when the two vectors are perpendicular and when they are parallel.


### **Problem 2.a: Vector Magnitude**

An inner product space makes a <b>norm/ length</b>, that is, a notion of length of a vector.

<br>Let $ V $ be an inner product space and let $v \in V $. The <b>norm/length</b> of $v$ is denoted $||v||$ and is defined by

$$ ||v|| = \sqrt{\langle v,v \rangle} $$

<i>the square root is defined by the property (i) of the inner product.</i>


<br><b><u>Example</b></u>: Find $||vect||$ where,

$$ vect = \begin{bmatrix} 2 & 4 \\ -3 & 7 \end{bmatrix} $$

<br><b><u>Solution</b></u>:

$$ ||vect|| = \sqrt{\langle vect,vect \rangle} $$  

$$ = \sqrt{\langle\begin{bmatrix} 2 & 4 \\ -3 & 7 \end{bmatrix}\rangle,\langle\begin{bmatrix} 2 & 4 \\ -3 & 7 \end{bmatrix}\rangle} $$

$$ = \sqrt{(2)(2) + (4)(4) + (-3)(-3) + (7)(7)} $$

$$ = \sqrt{4 + 16 + 9 + 49} $$

$$ vect = \sqrt{78} \space or \space 8.831760866327848 $$

<br> Putting this into code would be,

In [3]:
vect = np.array([2,4,-3,7])
vect_2 = np.array([2,4,-3,7])

answer = np.matmul(vect,vect_2)
answer

78

In [4]:
magnitude = np.sqrt(np.matmul(vect,vect_2))
print('The magnitude is the square root of', answer, 'or', magnitude)

The magnitude is the square root of 78 or 8.831760866327848


### **Problem 2.b: Angle Between Vectors**

<br> The <b>dot product</b> is a method for determining when two vectors are perpendicular and it will give another method for determining when two vectors are parallel. The term <b>orthogonal</b> is also used in place of perpendicular.

<br> If two vectors are <b>orthogonal (perpendicular)</b>, then, the angle between them is 90 degrees. From the Law of Cosines theorem, this tells that if two vectors are orthogonal then,

$$ u\cdot v=0$$

<br> With that being said, two vectors are considered to be orthogonal if their dot product <b>equals to 0</b>.

<br> Additionally, if two vectors are <b>parallel</b>, then the angle between them is either 0 degrees—pointing in the same direction, or 180 degrees—pointing in the opposite direction. Again, using the Law of Cosine theorem, this would mean that one of the following would have to be <i>true</i>.

$$ u\cdot v=||u||\cdot||v||\space(\theta=0^\circ)$$ $$OR$$ $$ u\cdot v=-||u||\cdot||v||\space(\theta=180^\circ)$$

<b><u>Example 1</u></b>:
$$ u=\langle 3,4 \rangle, v=\langle -8,6 \rangle $$

 <b><u>Solution</u></b>:
$$ \langle 3,4 \rangle\space\cdot\langle -8,6 \rangle $$
$$ = (3\times(-8))+4\times6 $$
$$ =-24+24 $$
$$ =0 $$

Therefore, this makes the vector <b>perpendicular</b>.

<br><b><u>Example 2</u></b>:
$$ u=\langle-9,18\rangle, v=\langle-3,6\rangle $$

<br><b><u>Solution</u></b>:
$$ u = -3v $$

Making the vector <b>parallel</b>:
$$ 3\langle-3,6\rangle=\langle-9,18\rangle $$

# Case 3
For the final cases analysis we will be looking at series of equations building up a single feed-forward computation of a logistic regression. The case will not require you to learn fully what is logistic regression. 

$$X = \begin{bmatrix} 
— (x^{(1)})^T— \\ 
— (x^{(2)})^T— \\
\vdots \\
— (x^{(m)})^T— \\
\end{bmatrix} \text{, } 
Y = \begin{bmatrix} 
y^{(1)} \\ 
y^{(2)} \\
\vdots \\
y^{(m)} \\
\end{bmatrix} \text{, and } 
\theta = \begin{bmatrix} 
\theta^{(1)} \\ 
\theta^{(2)} \\
\vdots \\
\theta^{(m)} \\
\end{bmatrix} $$
The dataset $X$ has $m$ entries with $n$ features while $Y$ is the vector containing the groud truths of a the entries of $X$, and $\theta$ are the parameters or weights of the vectors. We first compute the vector product of the dataset and the parameters as:
$$ z = x^{(i)}\theta^{(i)} = X\cdot \theta\\_{\text{Eq. 3.1}}$$
We then solve for the hypothesis of the logistic regression alogrithm as:

$$ h_\theta(x) = g(z)\\_{\text{Eq. 3.2}}$$

Where $g$ is an acitvation function that maps the values of the hypothesis vector between a range of 0 and 1. We computed the activation as a sigmoid function:
$$g(z) = \frac{1}{1+e^{-z}}\\_{\text{Eq. 3.3}}$$
Finally we compute the loss of the logistic regression algorithm using $J$. Wheras $J(\theta)$ is a function that computes the logistic loss of the hypothesis with respect to the ground truths $y$. it is then computed as:
$$J(\theta) = \frac{1}{m} \sum^m_{i=0}=[-y^{(i)}\log({h_{\theta}(x^{(i)})})-(1-y^{(i)})\log(1-h_{\theta}(x^{(i)}))]\\_{\text{Eq. 3.4}}$$

> **Problem 3.a: Matrix Equivalences**

> In Eq. 1, $z$ can also be solved as $X \cdot \theta$ which is the vectorized form of $x^{(i)}\theta^{(i)}$. However, it can also be expressed as $\theta^T\cdot X$. Prove the equality of $X \cdot \theta$ with $\theta^T\cdot X$ in this case.

> **Problem 3.b: Matrix Shapes**

> Determine the shape of $h_\theta$ if $X$ has a shape of $(300,5)$.

> **Problem 3.c: Vectorization**

> Express $J(\theta)$ into its vectorized form.

> **Problem 4.c: Computational Programming (Also Laboratory 2)**

> Encode Equations 3.1 to 3.4 as the class `LRegression` wherein:

> * `LRegression` should be instantiated with a dataset $X$, a ground truth vector $y$, and a parameter vector $\theta$. Each parameter should have a data type of `numpy.array`.
> * It should further have `methods`reflecting to at least the four (4) aforementioned equations. Each should have a return value.


### **Problem 3.a: Matrix Equivalences**

$$X = \begin{bmatrix} 
— (x^{(1)})^T— \\ 
— (x^{(2)})^T— \\
\vdots \\
— (x^{(m)})^T— \\
\end{bmatrix} \text{ ,} 
\theta = \begin{bmatrix} 
\theta^{(1)} \\ 
\theta^{(2)} \\
\vdots \\
\theta^{(m)} \\
\end{bmatrix} $$

$$X \cdot\theta = \begin{bmatrix} 
— (x^{(1)})^T\theta— \\ 
— (x^{(2)})^T\theta— \\
\vdots \\
— (x^{(m)})^T\theta— \\
\end{bmatrix} \ $$

$$\theta^T\cdot\ X = 
\begin{bmatrix} 
\\— \theta^T(x^{(1)} —) \\ 
\\— \theta^T(x^{(2)} —) \\
\vdots
\\— \theta^T(x^{(m)} — ) \\
\end{bmatrix} $$


using element-wise multiplication:
 $$X \cdot\theta = \theta^T\cdot\ X $$  
$$[(x^{(1)})^T\theta^{(1)} + (x^{(2)})^T\theta^{(2)}...+(x^{(m)})^T\theta^{(m)}] = [(x^{(1)})^T\theta^{(1)} + (x^{(2)})^T\theta^{(2)}...+(x^{(m)})^T\theta^{(m)}] $$








### **Problem 3.b: Matrix Shapes**

$$ X = \begin{bmatrix} a^1 & a^2 & a^3 & a^4 & a^5 \\ a^6 & a^7 & a^8 & a^9 & a^{10} \\ \vdots & \vdots & \vdots & \vdots & \vdots\\  a^{296} & a^{297} & a^{298} & a^{299} & a^{300} \end{bmatrix} \text{ , } \theta = \begin{bmatrix} 
 (\theta^1) \\ 
 (\theta^2) \\
\vdots \\
 (\theta^k) \\
\end{bmatrix} \ $$

The sigmoid function definition is:
$$g(z) = \frac{1}{1+e^{-z}}$$

The process can be written with matrix operation:
$$ z = X \cdot\theta $$

$$ h_\theta(x) = g( X \cdot\theta)$$


$$ h_\theta(x) = g(z) $$

After applying multiplication between $(k \cdot 1)$ and $(m\cdot k)$ dimension we get a number z , then the z is passed to sigmoid function and we will have the final result of $h_\theta(x)$. The equation can be merged into one therefore the matrix shape of the $ h_\theta(x)$ would be the same as the matrix X.
$$ h_\theta(x) = \begin{bmatrix} \theta^1(a) & \theta^2(a) & \theta^3(a) & \theta^4(a) & \theta^5(a)\\ \theta^6(a) & \theta^7(a) & \theta^8(a) & \theta^9(a) & \theta^{10}(a) \\ \vdots & \vdots & \vdots & \vdots & \vdots\\  \theta^{296}(a) & \theta^{297}(a) & \theta^{298}(a) & \theta^{299}(a) & \theta^{300}(a) \end{bmatrix}$$

### **Problem 3.c: Vectorization**

The partial derivatives of $(\theta_j)$

$$\begin{bmatrix} 
\frac{\partial{J}}{\partial{\theta}_0} \\ 
\frac{\partial{J}}{\partial{\theta}_1} \\
\frac{\partial{J}}{\partial{\theta}_2} \\
\vdots \\
\frac{\partial{J}}{\partial{\theta}_n} \\
\end{bmatrix} = 
\frac{1}{m}
\begin{bmatrix} 
\sum^{m}_{i=1} [ -y^{(i)} \log (h_{\theta} (x^{(i)})) - (1-y^{(i)}) \log (1-h_{\theta}(x^{(i)}))] \\
\sum^{m}_{i=1} [ -y^{(i)} \log (h_{\theta} (x^{(i)})) - (1-y^{(i)}) \log (1-h_{\theta}(x^{(i)}))] \\ 
\sum^{m}_{i=1} [ -y^{(i)} \log (h_{\theta} (x^{(i)})) - (1-y^{(i)}) \log (1-h_{\theta}(x^{(i)}))] \\ 
\vdots \\
\sum^{m}_{i=1} [ -y^{(i)} \log (h_{\theta} (x^{(i)})) - (1-y^{(i)}) \log (1-h_{\theta}(x^{(i)}))] \\ 
\end{bmatrix} 
$$

Since the partial derivatives were expressed, the gradient vector is formed as:
$$
\frac{\partial{J}(\theta)}{\partial{\theta}_0} =
\frac{1}{m}
\sum\limits_{i=1}^m (h_0(x^{(i)})-y^{(i)})x^{(i)}_j 
$$
Therefore the vectorized form of $J(\theta)$ is: 
$$
\\=\frac{1}{m}X^T(h_\theta(x)-y))
$$



### **Problem 4.c: Computational Programming (Also Laboratory 2)**

In [5]:
class LRegression():
  def __init__(self, X_array, y_GndTruth, thetaVector):
    self.X_array = X_array
    self.y_GndTruth = y_GndTruth
    self.thetaVector = thetaVector
  
  def getVectorMagnitude(self):
    magnitude = np.linalg.norm(self.thetaVector)
    return magnitude
  
  def getZ(self): #Eq. 3.1
    self.z = np.dot(self.X_array, self.thetaVector)
    return self.z

  def getActivation (self): #Eq. 3.2 & 3.3
    self.activation = 1/(1+np.exp(self.z))
    return self.activation

  def getLoss(self): #Eq. 3.4
    m = self.y_GndTruth.shape[0]
    yt = self.y_GndTruth.transpose()

    lossEq= (-1*yt)*(np.log(self.activation)) - ((1-self.y_GndTruth).transpose())*(np.log(1-self.activation))
    self.J = (1/m)*lossEq
    return self.J

In [6]:
X = np.array([[1,2,3],
              [1,2,3],
              [4,5,6],])
m = X.shape[1]
theta = np.random.normal(0, 1, size=(m, 1))
y = np.random.randint(0,2, size=(m,1))
Regression = LRegression(X, y, theta)

In [7]:
Regression.getVectorMagnitude()

1.0716158574454309

In [8]:
Regression.getZ()

array([[2.71621582],
       [2.71621582],
       [7.75637269]])

In [9]:
Regression.getActivation()

array([[0.06202325],
       [0.06202325],
       [0.00042782]])

In [10]:
Regression.getLoss()

array([[9.26748645e-01, 2.13433730e-02, 2.13433730e-02],
       [9.26748645e-01, 2.13433730e-02, 2.13433730e-02],
       [2.58560020e+00, 1.42638237e-04, 1.42638237e-04]])