<a href="https://colab.research.google.com/drive/1seYGbBHco1FdwJEdLrv2GcqJkoqVAuPp" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> **Problem 4.c: Computational Programming (Also Laboratory 2)**

> Encode Equations 3.1 to 3.4 as the class `LRegression` wherein:

> * `LRegression` should be instantiated with a dataset $X$, a ground truth vector $y$, and a parameter vector $\theta$. Each parameter should have a data type of `numpy.array`.
> * It should further have `methods`reflecting to at least the four (4) aforementioned equations. Each should have a return value.


In [1]:
import numpy as np
from numpy import random

In [8]:
class LRegression():
  def __init__(self, X_array, y_GndTruth, thetaVector):
    self.X_array = X_array
    self.y_GndTruth = y_GndTruth
    self.thetaVector = thetaVector
  
  def getVectorMagnitude(self):
    magnitude = np.linalg.norm(self.thetaVector)
    return magnitude
  
  def getZ(self): #Eq. 3.1
    self.z = np.dot(self.X_array, self.thetaVector)
    return self.z

  def getActivation (self): #Eq. 3.2 & 3.3
    self.activation = 1/(1+np.exp(self.z))
    return self.activation

  def getLoss(self): #Eq. 3.4
    m = self.y_GndTruth.shape[0]
    yt = self.y_GndTruth.transpose()    
    lossEq = (-1*yt)*np.sum(np.multiply(np.log(self.activation), self.y_GndTruth)) - ((1-self.y_GndTruth).transpose())*(np.log(1-self.activation))
    self.J = (1/m)*lossEq
    return self.J

In [9]:
X = np.array([[2,4,6],
              [1,7,9],
              [3,5,8],])
m = X.shape[1]
theta = np.random.normal(0, 1, size=(m, 1))
y = np.random.randint(0,2, size=(m,1))
Regression = LRegression(X, y, theta)

In [10]:
Regression.getVectorMagnitude()

1.5202314307868783

###Equation 3.1

$$ z = x^{(i)}\theta^{(i)} = X\cdot \theta\\_{\text{Eq. 3.1}}$$

In [11]:
Regression.getZ()

array([[3.30956746],
       [8.1821339 ],
       [3.75506618]])

###Equation 3.2 and 3.3

$$ h_\theta(x) = g(z)\\_{\text{Eq. 3.2}}$$

$$g(z) = \frac{1}{1+e^{-z}}\\_{\text{Eq. 3.3}}$$

In [12]:
Regression.getActivation()

array([[0.03524442],
       [0.00027953],
       [0.02286391]])

###Equation 3.4

$$J(\theta) = \frac{1}{m} \sum^m_{i=0}=[-y^{(i)}\log({h_{\theta}(x^{(i)})})-(1-y^{(i)})\log(1-h_{\theta}(x^{(i)}))]\\_{\text{Eq. 3.4}}$$

In [13]:
Regression.getLoss()

array([[1.19601662e-02, 2.72747115e+00, 1.19601662e-02],
       [9.31885243e-05, 2.72747115e+00, 9.31885243e-05],
       [7.70978151e-03, 2.72747115e+00, 7.70978151e-03]])